"use client";

import { motion } from "framer-motion";
import { Share2, ExternalLink, Flame, Download } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { ScoreCard } from "./score-card";
import { RoastCard } from "./roast-card";
import type { AnalysisResult } from "@/types";
import Link from "next/link";
import Image from "next/image";

export function PublicRoastView({
  result,
  slug,
}: {
  result: AnalysisResult;
  slug?: string;
}) {
  const handleShare = () => {
    const text = `Check out this website roast by @RoastIQ\n\nScore: ${result.overallScore}/100\n\nGet your website roasted at roastiq.ai`;
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`;
    window.open(twitterUrl, "_blank");
  };

  return (
    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center mb-8"
      >
        <div className="inline-flex items-center gap-2 rounded-full border border-roast/30 bg-roast/10 px-4 py-1.5 text-sm text-roast mb-4">
          <Flame className="h-3.5 w-3.5" />
          Public Roast
        </div>
        <h1 className="text-3xl font-bold mb-2">
          Roast for{" "}
          <span className="gradient-text">{result.url}</span>
        </h1>
        <p className="text-sm text-muted-foreground">
          Generated by RoastIQ AI Analysis Engine
        </p>
      </motion.div>

      {result.screenshotUrl && (
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.05 }}
          className="glass rounded-2xl overflow-hidden max-w-3xl mx-auto mb-8"
        >
          <Image
            src={result.screenshotUrl}
            alt={`Screenshot of ${result.url}`}
            width={1280}
            height={800}
            className="w-full h-auto"
          />
        </motion.div>
      )}

      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.1 }}
        className="glass rounded-2xl p-8 text-center max-w-md mx-auto mb-8"
      >
        <div className="text-6xl font-bold gradient-text mb-2">
          {result.overallScore}
        </div>
        <p className="text-sm text-muted-foreground mb-4">/100 Overall Score</p>
        <div className="flex items-center justify-center gap-3 flex-wrap">
          <Button size="sm" variant="outline" onClick={handleShare}>
            <Share2 className="mr-1.5 h-3.5 w-3.5" />
            Share on X
          </Button>
          {slug && (
            <Link
              href={`/api/report?scanId=${result.id}`}
              target="_blank"
              className={cn(buttonVariants({ size: "sm", variant: "outline" }))}
            >
              <Download className="mr-1.5 h-3.5 w-3.5" />
              Download PDF
            </Link>
          )}
          <Link
            href="/roast"
            className={cn(
              buttonVariants({ size: "sm" }),
              "roast-gradient text-white border-0"
            )}
          >
            <ExternalLink className="mr-1.5 h-3.5 w-3.5" />
            Roast Your Site
          </Link>
        </div>
      </motion.div>

      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8">
        {result.scores.map((score, i) => (
          <ScoreCard key={score.name} score={score} index={i} />
        ))}
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mb-12">
        {result.roastComments.map((comment, i) => (
          <RoastCard key={comment.category} comment={comment} index={i} />
        ))}
      </div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        className="glass rounded-2xl p-8 text-center"
      >
        <h2 className="text-2xl font-bold mb-3">
          Want Your Website <span className="gradient-text">Roasted?</span>
        </h2>
        <p className="text-sm text-muted-foreground mb-6">
          Get your own AI-powered analysis in seconds. No signup required.
        </p>
        <Link
          href="/#analyze"
          className={cn(
            buttonVariants({ size: "lg" }),
            "roast-gradient text-white border-0 hover:opacity-90"
          )}
        >
          Roast My Website
        </Link>
      </motion.div>
    </div>
  );
}
