import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { jsPDF } from "jspdf";

interface ScoreData {
  name: string;
  score: number;
  description: string;
}

interface RoastComment {
  category: string;
  comment: string;
  severity: string;
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const scanId = searchParams.get("scanId");

    if (!scanId) {
      return NextResponse.json({ error: "scanId is required" }, { status: 400 });
    }

    const scan = await prisma.scan.findUnique({ where: { id: scanId } });
    if (!scan) {
      return NextResponse.json({ error: "Scan not found" }, { status: 404 });
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Header
    doc.setFillColor(20, 20, 30);
    doc.rect(0, 0, pageWidth, 50, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("RoastIQ", 20, y + 10);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("AI Website Roast & Conversion Analysis", 20, y + 20);
    doc.setFontSize(8);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 20, y + 20, { align: "right" });

    y = 60;

    // Website URL
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Website Analyzed", 20, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(scan.url, 20, y + 8);
    doc.text(`Mode: ${scan.mode.charAt(0).toUpperCase() + scan.mode.slice(1)}`, 20, y + 16);

    y += 30;

    // Overall Score
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Overall Score", 20, y);
    doc.setFontSize(36);
    const scoreColor = scan.overallScore >= 70 ? [34, 197, 94] : scan.overallScore >= 50 ? [234, 179, 8] : [239, 68, 68];
    doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.text(`${scan.overallScore}/100`, pageWidth / 2, y + 5, { align: "center" });
    doc.setTextColor(0, 0, 0);

    y += 25;

    // Category Scores
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Category Scores", 20, y);
    y += 10;

    const scores = scan.scores as unknown as ScoreData[];
    doc.setFontSize(9);
    for (const score of scores) {
      doc.setFont("helvetica", "bold");
      doc.text(`${score.name}: ${score.score}/100`, 25, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 100, 100);
      doc.text(score.description || "", 25, y + 5, { maxWidth: pageWidth - 50 });
      doc.setTextColor(0, 0, 0);
      y += 14;
      if (y > 270) { doc.addPage(); y = 20; }
    }

    y += 5;

    // Roast Comments
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Roast Comments", 20, y);
    y += 10;

    const comments = scan.roastComments as unknown as RoastComment[];
    doc.setFontSize(9);
    for (const c of comments) {
      doc.setFont("helvetica", "bold");
      doc.text(`${c.category} [${c.severity}]`, 25, y);
      doc.setFont("helvetica", "italic");
      const lines = doc.splitTextToSize(`"${c.comment}"`, pageWidth - 50);
      doc.text(lines, 25, y + 5);
      y += 5 + lines.length * 4.5;
      if (y > 270) { doc.addPage(); y = 20; }
    }

    y += 5;

    // Professional Feedback
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Professional Feedback", 20, y);
    y += 10;

    const feedback = scan.professionalFeedback as unknown as string[];
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    for (const item of feedback) {
      const lines = doc.splitTextToSize(`• ${item}`, pageWidth - 50);
      doc.text(lines, 25, y);
      y += lines.length * 4.5 + 2;
      if (y > 270) { doc.addPage(); y = 20; }
    }

    y += 5;

    // Redesign Suggestions
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Redesign Suggestions", 20, y);
    y += 10;

    const suggestions = scan.redesignSuggestions as unknown as string[];
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    for (const item of suggestions) {
      const lines = doc.splitTextToSize(`• ${item}`, pageWidth - 50);
      doc.text(lines, 25, y);
      y += lines.length * 4.5 + 2;
      if (y > 270) { doc.addPage(); y = 20; }
    }

    // Footer
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by RoastIQ — roastiq.ai", 20, 290);
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - 20, 290, { align: "right" });
    }

    const pdfBuffer = doc.output("arraybuffer");

    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="roastiq-report-${scan.slug || scan.id}.pdf"`,
      },
    });
  } catch (error) {
    console.error("Report generation error:", error);
    return NextResponse.json({ error: "Failed to generate report" }, { status: 500 });
  }
}
